// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-DkZxgvpBdyZKVF2CbtRJRHTxxstFunU',
    appId: '1:632786820842:web:cb5ac10033c3a0cf4ec193',
    messagingSenderId: '632786820842',
    projectId: 'cityzen-5c98c',
    authDomain: 'cityzen-5c98c.firebaseapp.com',
    storageBucket: 'cityzen-5c98c.firebasestorage.app',
    measurementId: 'G-PSHJEZGMSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-CityZen-Android-Development',
    appId: '1:123456789:android:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'cityzen-demo-project',
    storageBucket: 'cityzen-demo-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-CityZen-iOS-Development',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'cityzen-demo-project',
    storageBucket: 'cityzen-demo-project.appspot.com',
    iosBundleId: 'com.example.cityzen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-CityZen-macOS-Development',
    appId: '1:123456789:ios:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'cityzen-demo-project',
    storageBucket: 'cityzen-demo-project.appspot.com',
    iosBundleId: 'com.example.cityzen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKey-CityZen-Windows-Development',
    appId: '1:123456789:web:abcdef123456789',
    messagingSenderId: '123456789',
    projectId: 'cityzen-demo-project',
    authDomain: 'cityzen-demo-project.firebaseapp.com',
    storageBucket: 'cityzen-demo-project.appspot.com',
    measurementId: 'G-MEASUREMENT_ID',
  );
}